apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: java-springboot-okjccrov
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-okjccrov 
  name: java-springboot-okjccrov
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-springboot-okjccrov
    weight: 100 
